no=int(input("enter a number: "))
no2=int(input("enter a number: "))
print(f"addition       of {no} and {no2} is {no+no2}")
print(f"subtraction    of {no} and {no2} is {no-no2}")
print(f"multiplication of {no} and {no2} is {no*no2}")
print(f"division       of {no} and {no2} is {no/no2}")
print(f"modulus        of {no} and {no2} is {no%no2}")
print(f"exponent       of {no} and {no2} is {no**no2}")
print(f"floor division of {no} and {no2} is {no//no2}") 