num1=int(input("enter a number: "))
num2=int(input("enter a number:"))
print(f"{num1} > {num2} is {num1>num2}")
print(f"{num1} < {num2} is {num1<num2}")
print(f"{num1} != {num2} is {num1!=num2}")
print(f"{num1} == {num2} is {num1==num2}") 
print(f"{num1} >= {num2} is {num1>=num2}")
print(f"{num1} <= {num2} is {num1<=num2}")